<!doctype html>
<html>

	<head>
		<!-- Include a required theme -->
		<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
		<meta charset="utf-8">
		<title> ğƒ ğ® ğ¨ ğ§ ğ  ğŒ ğ¢ ğ§ ğ¡ ğƒ ğ® ğ§ ğ  <3</title>
		<style type="text/css">
			/* CSS Document */
			* {
				margin: 0;
				padding: 0;
			}

			a {
				text-decoration: none;
			}

			.clearfix:after {
				content: "";
				display: block;
				height: 0;
				visibility: hidden;
				clear: both;
			}

			.clearfix {
				*zoom: 1;
			}

			body {
				background: url(https://khoinguonsangtao.vn/wp-content/uploads/2021/09/hinh-anh-gif-anime.gif) no-repeat;
				background-size: cover;
				background-attachment: fixed;
			}

			.content {
				width: 900px;
				height: 500px;
				margin: 200px auto 0 auto;
				border-radius: 10px;
				background-color: rgba(236, 236, 236, 0.59);
				transition: all 1.0s;
				/*box-shadow: 0px 0px 20px rgba(0,0,0,0.3);*/
			}

			.content img {
				float: left;
				width: 200px;
				height: 200px;
				margin: 150px 0 0 80px;
				border-radius: 100px;

			}

			.content:hover {
				box-shadow: 0px 0px 20px rgb(0, 162, 255);
			}

			.content_r {
				float: right;
				width: 500px;
				margin: 80px 60px 0 0;
				/*	background-color: pink;*/
			}

			.content_l {
				float: left;
				width: 100%;
				text-align: center;
			}

			.content_l h5 {

				font-size: 17px;
			}

			.bio {
				margin-top: 10px;
				color: #1F2023;
				font-size: 18px;
			}

			.color_1 {
				color: #4855EC;
				font-size: 18px;
			}

			.deeppink {
				color: deeppink;
			}

			.link {
				margin-top: 30px;
			}

			.link a {
				display: block;
				float: left;
				width: 120px;
				height: 45px;
				margin: 5px 5px 0 0;
				/*	padding: 0 15px;*/
				color: #fff;
				line-height: 45px;
				transition: all 0.8s;
				/*	background-color: deeppink;*/

			}

			.link a:hover {
				background-color: rgba(0, 0, 0, 0.35);
                box-shadow: 0px 0px 20px rgb(61, 196, 230);
			}

			.black {
				background-color: rgb(36, 35, 35);
			}

			.dodgerblue {
				background-color: dodgerblue;
			}

			.green {
				background-color: rgb(0, 211, 248);
			}

			.red {
				background-color: rgb(216, 25, 25);
			}
		</style>
		<!---->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="shortcut icon" href="https://i.imgur.com/19OcWjh.jpg" type="image/x-icon">
	<link rel="me" href="https://www.blogger.com/profile/14696126482400772705" />
<meta name='google-adsense-platform-account' content='ca-host-pub-1556223355139109'/>
<meta name='google-adsense-platform-domain' content='blogspot.com'/>
<!-- --><style type="text/css">@import url(//www.blogger.com/static/v1/v-css/navbar/3334278262-classic.css);
div.b-mobile {display:none;}
</style>

</head>
	<body onclick="audio.play()"><script type="text/javascript">
    function setAttributeOnload(object, attribute, val) {
      if(window.addEventListener) {
        window.addEventListener('load',
          function(){ object[attribute] = val; }, false);
      } else {
        window.attachEvent('onload', function(){ object[attribute] = val; });
      }
    }
  </script>
<div id="navbar-iframe-container"></div>
<script type="text/javascript" src="https://apis.google.com/js/platform.js"></script>
<script type="text/javascript">
      gapi.load("gapi.iframes:gapi.iframes.style.bubble", function() {
        if (gapi.iframes && gapi.iframes.getContext) {
          gapi.iframes.getContext().openChild({
              url: 'https://www.blogger.com/navbar.g?targetBlogID\x3d7667180299849229556\x26blogName\x3dD%C6%B0%C6%A1ng+D%C5%A9ng+\x26publishMode\x3dPUBLISH_MODE_BLOGSPOT\x26navbarType\x3dSILVER\x26layoutType\x3dCLASSIC\x26searchRoot\x3dhttps://duongdunginfo.blogspot.com/search\x26blogLocale\x3dvi\x26v\x3d2\x26homepageUrl\x3dhttps://duongdunginfo.blogspot.com/\x26vt\x3d1673637926770329889',
              where: document.getElementById("navbar-iframe-container"),
              id: "navbar-iframe"
          });
        }
      });
    </script>	
		<div class="content">
			<img src="https://i.imgur.com/a6hZKlt.jpg" alt="">
			<div class="content_r clearfix">
				<div class="content_l clearfix">
					<h2>ã“ã‚“ã«ã¡ã¯ã€DÆ°Æ¡ng DÅ©ng ã¯ã˜ã‚ã¾ã—ã¦ </h2>
					<p class="bio">  ğ¼ ğ¿ğ‘‚ğ‘‰ğ¸ ğ‘Œğ‘‚ğ‘ˆ  </p>
					<p class="bio">  ..ğ¼ğ‘ ğ¸ğ‘‰ğ¸ğ‘…ğ‘Œ ğ‘ˆğ‘ğ¼ğ‘‰ğ¸ğ‘…ğ‘†ğ¸   ! </p>
					<br>
					<p class="color_3">O P E R A T O Rã…¤ã…¤:ã…¤ã…¤D U O N Gã…¤ã…¤M I N Hã…¤ã…¤D U N Gã…¤ã…¤ï¼œï¼“</p>
					<!-- <p class="color_1"></p> -->
					<br>
					<p class="deeppink">/ã…¤Fã…¤Oã…¤Rã…¤Eã…¤Vã…¤Eã…¤Rã…¤/</p>
					<div class="link">
						<a href="https://www.facebook.com/duongdung18th1/ " class="dodgerblue" target="_blank"><i class=""></i> Facebook</a>
						<a href="" class="pink" target=""><i class=""></i>ğ—¢ğ—¿ ğ—”ğ—»ğ—¼ğ˜ğ—µğ—²ğ—¿ ğ—ªğ—®ğ˜†</a>
						<a href="" class="" target=""><i class="" aria-hidden="true"></i>ğ—§ğ—¼ ğ—šğ—²ğ˜ ğ—œğ—» ğ—§ğ—¼ğ˜‚ğ—°ğ—µ</a>
						<a href="https://www.tiktok.com/@_mdung.ye" class="black" target="_blank"><i class="fa-brands fa-tiktok"></i> Tiktok</a>
				</div>
			</div>
		</div>
		<script>
			var audio = new Audio('https://rr3---sn-8qj-i5osr.googlevideo.com/videoplayback?expire=1712242344&ei=SGoOZsqQLvSz1d8P-Kmz0AE&ip=14.191.145.122&id=o-AHgFkL9-uLUPV9qTLIyKoYdgr-1FWq32WkkhJJyAOU9z&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=63&mm=31%2C29&mn=sn-8qj-i5osr%2Csn-8qj-i5oll&ms=au%2Crdu&mv=m&mvi=3&pl=24&initcwndbps=1718750&bui=AaUN6a0TNMa0T0fqUbUv-gPx2z5ouT55j-BeoNJz7lL5W5xEnQu-hEL7MnFlLcI_xUNqHEeu9mWzuwU6&spc=UWF9f0xz8McpuERI55UVp-osmf45DE_RophUBmn5ASEyFOI&vprv=1&svpuc=1&mime=video%2Fmp4&ns=6b8qx0aj1qgrQwxvc0NEzE4Q&cnr=14&ratebypass=yes&dur=2515.974&lmt=1698770477217731&mt=1712220297&fvip=8&fexp=51141541&c=WEB&sefc=1&txp=5319224&n=LQZgr2mF8xj9NCs7e&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALClDIEwRQIhAOfUPswOM8-dSRV9vrykXdLlU8IPBno_qtzl5SUB4UKSAiAZ5qvn-Q5g70AymPQfgc_BSWQ4w7c0_sSh4yLgzogTDA%3D%3D&sig=AJfQdSswRQIgbRaV6JXBWc1oyj1VpMJUfzSiJJ1Obwz3ebkZYtzC9dwCIQDfSUM-BXt1AOg11JIpCUG1UbvEliHlryCwH0oTAnReDg%3D%3D');
      
			audio.oncanplaythrough = function(){
			audio.play();
			}
			
			audio.loop = true;
			
			audio.onended = function(){
			audio.play();
			}
   
		</script>
        <script>

//â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬
   // HOA ANH DAO
//â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬
var stop, staticx;
var img = new Image();
img.src = "";

			function Sakura(x, y, s, r, fn) {
				this.x = x;
				this.y = y;
				this.s = s;
				this.r = r;
				this.fn = fn;
			}

			Sakura.prototype.draw = function(cxt) {
				cxt.save();
				var xc = 40 * this.s / 4;
				cxt.translate(this.x, this.y);
				cxt.rotate(this.r);
				cxt.drawImage(img, 0, 0, 40 * this.s, 40 * this.s)
				cxt.restore();
			}

			Sakura.prototype.update = function() {
				this.x = this.fn.x(this.x, this.y);
				this.y = this.fn.y(this.y, this.y);
				this.r = this.fn.r(this.r);
				if(this.x > window.innerWidth ||
					this.x < 0 ||
					this.y > window.innerHeight ||
					this.y < 0
				) {
					this.r = getRandom('fnr');
					if(Math.random() > 0.4) {
						this.x = getRandom('x');
						this.y = 0;
						this.s = getRandom('s');
						this.r = getRandom('r');
					} else {
						this.x = window.innerWidth;
						this.y = getRandom('y');
						this.s = getRandom('s');
						this.r = getRandom('r');
					}
				}
			}

			SakuraList = function() {
				this.list = [];
			}
			SakuraList.prototype.push = function(sakura) {
				this.list.push(sakura);
			}
			SakuraList.prototype.update = function() {
				for(var i = 0, len = this.list.length; i < len; i++) {
					this.list[i].update();
				}
			}
			SakuraList.prototype.draw = function(cxt) {
				for(var i = 0, len = this.list.length; i < len; i++) {
					this.list[i].draw(cxt);
				}
			}
			SakuraList.prototype.get = function(i) {
				return this.list[i];
			}
			SakuraList.prototype.size = function() {
				return this.list.length;
			}

			function getRandom(option) {
				var ret, random;
				switch(option) {
					case 'x':
						ret = Math.random() * window.innerWidth;
						break;
					case 'y':
						ret = Math.random() * window.innerHeight;
						break;
					case 's':
						ret = Math.random();
						break;
					case 'r':
						ret = Math.random() * 5;
						break;
					case 'fnx':
						random = -0.5 + Math.random() * 1;
						ret = function(x, y) {
							return x + 0.5 * random - 1;
						};
						break;
					case 'fny':
						random = 0.5 + Math.random() * 0.5
						ret = function(x, y) {
							return y + random;
						};
						break;
					case 'fnr':
						random = Math.random() * 0.01;
						ret = function(r) {
							return r + random;
						};
						break;
				}
				return ret;
			}

			function startSakura() {

				requestAnimationFrame = window.requestAnimationFrame ||
					window.mozRequestAnimationFrame ||
					window.webkitRequestAnimationFrame ||
					window.msRequestAnimationFrame ||
					window.oRequestAnimationFrame;
				var canvas = document.createElement('canvas'),
					cxt;
				staticx = true;
				canvas.height = window.innerHeight;
				canvas.width = window.innerWidth;
				canvas.setAttribute('style', 'position: fixed;left: 0;top: 0;pointer-events: none;');
				canvas.setAttribute('id', 'canvas_sakura');
				document.getElementsByTagName('body')[0].appendChild(canvas);
				cxt = canvas.getContext('2d');
				var sakuraList = new SakuraList();
				for(var i = 0; i < 50; i++) {
					var sakura, randomX, randomY, randomS, randomR, randomFnx, randomFny;
					randomX = getRandom('x');
					randomY = getRandom('y');
					randomR = getRandom('r');
					randomS = getRandom('s');
					randomFnx = getRandom('fnx');
					randomFny = getRandom('fny');
					randomFnR = getRandom('fnr');
					sakura = new Sakura(randomX, randomY, randomS, randomR, {
						x: randomFnx,
						y: randomFny,
						r: randomFnR
					});
					sakura.draw(cxt);
					sakuraList.push(sakura);
				}
				stop = requestAnimationFrame(function() {
					cxt.clearRect(0, 0, canvas.width, canvas.height);
					sakuraList.update();
					sakuraList.draw(cxt);
					stop = requestAnimationFrame(arguments.callee);
				})
			}

			window.onresize = function() {
				var canvasSnow = document.getElementById('canvas_snow');
				canvasSnow.width = window.innerWidth;
				canvasSnow.height = window.innerHeight;
			}

			img.onload = function() {
				startSakura();
			}

			function stopp() {
				if(staticx) {
					var child = document.getElementById("canvas_sakura");
					child.parentNode.removeChild(child);
					window.cancelAnimationFrame(stop);
					staticx = false;
				} else {
					startSakura();
				}
			}
		
			


//////////////////////////////////////////////////////////////

        </script>

		<script>
			Swal.fire();

			Swal.fire(
				'ğ· ğ‘¢ ğ‘œ ğ‘› ğ‘”ã…¤ğ‘€ ğ‘– ğ‘› â„ã…¤ğ· ğ‘¢ ğ‘› ğ‘”ã…¤<3',
				'Fã…¤Oã…¤Rã…¤Eã…¤Vã…¤Eã…¤R',
				'SUCCESS'
			)
		</script>
	</body>
</html>
      
